In [4]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd

# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [5]:
df = pd.read_csv('files/Tinder_Data_v3_Clean_Edition.csv')

In [6]:
df.head(2)

,_id,sum_app_opens,no_of_days,nrOfConversations,longestConversation,longestConversationInDays,averageConversationLength,averageConversationLengthInDays,medianConversationLength,medianConversationLengthInDays,nrOfOneMessageConversations,percentOfOneMessageConversations,nrOfGhostingsAfterInitialMessage,no_of_matches,no_of_msgs_sent,no_of_msgs_received,swipe_likes,swipe_passes,birthDate,ageFilterMin,ageFilterMax,cityName,country,createDate,education,gender,interestedIn,instagram,spotify,jobTitle,user_age
0,00b74e27ad1cbb2ded8e907fcc49eaaf,6839,477,739,133,684,8.56,10.24,3,0.081134,226,30.58,66,3408,3360,3261,23341,24229,1976-01-01,21,35,Trondheim,Norway,2016-01-01,Has high school and/or college education,M,F,False,False,unknown,40
1,024610702baf540af5637873cd1534e9,26280,1197,464,36,622,4.50,3.97,2,0.000069,56,12.07,16,888,2088,1509,45068,49559,1997-07-04,18,29,Richmond,USA,2016-07-12,Has high school and/or college education,M,F,False,False,unknown,19

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1209 entries, 0 to 1208
Data columns (total 31 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   _id                               1209 non-null   object
 1   sum_app_opens                     1209 non-null   int64
 2   no_of_days                        1209 non-null   int64
 3   nrOfConversations                 1209 non-null   int64
 4   longestConversation               1209 non-null   int64
 5   longestConversationInDays         1209 non-null   int64
 6   averageConversationLength         1209 non-null   float64
 7   averageConversationLengthInDays   1209 non-null   float64
 8   medianConversationLength          1209 non-null   int64
 9   medianConversationLengthInDays    1209 non-null   float64
 10  nrOfOneMessageConversations       1209 non-null   int64
 11  percentOfOneMessageConversations  1209 non-null   float64
 12  nrOfGhostingsAfterInitialMessage  1209 non-null   int64
 13  no_of_matches                     1209 non-null   int64
 14  no_of_msgs_sent                   1209 non-null   int64
 15  no_of_msgs_received               1209 non-null   int64
 16  swipe_likes                       1209 non-null   int64
 17  swipe_passes                      1209 non-null   int64
 18  birthDate                         1209 non-null   object
 19  ageFilterMin                      1209 non-null   int64
 20  ageFilterMax                      1209 non-null   int64
 21  cityName                          1209 non-null   object
 22  country                           1209 non-null   object
 23  createDate                        1209 non-null   object
 24  education                         1209 non-null   object
 25  gender                            1209 non-null   object
 26  interestedIn                      1209 non-null   object
 27  instagram                         1209 non-null   bool
 28  spotify                           1209 non-null   bool
 29  jobTitle                          1209 non-null   object
 30  user_age                          1209 non-null   int64
dtypes: bool(2), float64(4), int64(16), object(9)
memory usage: 276.4+ KB

In [10]:
def exploracion(df):
    df_info = pd.DataFrame()
    df_info["% nulos"] = round(df.isna().sum()/df.shape[0]*100, 2).astype(str)+"%"
    df_info["% no_nulos"] = round(df.notna().sum()/df.shape[0]*100, 2).astype(str)+"%"
    df_info["tipo_dato"] = df.dtypes
    df_info["num_valores_unicos"] = df.nunique()
    print(f"""El DataFrame tiene {df.shape[0]} filas y {df.shape[1]} columnas.
Tiene {df.duplicated().sum()} datos duplicados, lo que supone un porcentaje de {round(df.duplicated().sum()/df.shape[0], 2)}% de los datos.
Hay {len(list(df_info[(df_info["% nulos"] != "0.0%")].index))} columnas con datos nulos, y son:
{list(df_info[(df_info["% nulos"] != "0.0%")].index)}
y sin nulos hay {len(list(df_info[(df_info["% nulos"] == "0.0%")].index))} columnas y son:
{list(df_info[(df_info["% nulos"] == "0.0%")].index)}
A continuación tienes un detalle sobre los datos nulos y los tipos y número de datos:""")
    display(df_info.head())
    print("Principales estadísticos de las columnas categóricas:")
    display(df.describe(include="O").T)
    print("Principales estadísticos de las columnas numéricas:")
    display(df.describe(exclude="O").T)
    return df_info

In [11]:
exploracion(df)

El DataFrame tiene 1209 filas y 31 columnas.
Tiene 0 datos duplicados, lo que supone un porcentaje de 0.0% de los datos.
Hay 0 columnas con datos nulos, y son:
[]
y sin nulos hay 31 columnas y son:
['_id', 'sum_app_opens', 'no_of_days', 'nrOfConversations', 'longestConversation', 'longestConversationInDays', 'averageConversationLength', 'averageConversationLengthInDays', 'medianConversationLength', 'medianConversationLengthInDays', 'nrOfOneMessageConversations', 'percentOfOneMessageConversations', 'nrOfGhostingsAfterInitialMessage', 'no_of_matches', 'no_of_msgs_sent', 'no_of_msgs_received', 'swipe_likes', 'swipe_passes', 'birthDate', 'ageFilterMin', 'ageFilterMax', 'cityName', 'country', 'createDate', 'education', 'gender', 'interestedIn', 'instagram', 'spotify', 'jobTitle', 'user_age']
A continuación tienes un detalle sobre los datos nulos y los tipos y número de datos:

                    % nulos % no_nulos tipo_dato  num_valores_unicos
_id                    0.0%     100.0%    object                1209
sum_app_opens          0.0%     100.0%     int64                 927
no_of_days             0.0%     100.0%     int64                 595
nrOfConversations      0.0%     100.0%     int64                 449
longestConversation    0.0%     100.0%     int64                 356

Principales estadísticos de las columnas categóricas:

             count unique                                      top  freq
_id           1209   1209         00b74e27ad1cbb2ded8e907fcc49eaaf     1
birthDate     1209   1071                               2000-07-09     4
cityName      1209    444                                  unknown   480
country       1209     57                                  unknown   481
createDate    1209    879                               2021-08-06     5
education     1209      2  Has no high school or college education  1000
gender        1209      2                                        M  1059
interestedIn  1209      3                                        F  1018
jobTitle      1209    314                                  unknown   757

Principales estadísticos de las columnas numéricas:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
sum_app_opens,1209.0,NaN,NaN,NaN,4593.923077,8501.985991,0.0,236.0,1916.0,5445.0,92628.0
no_of_days,1209.0,NaN,NaN,NaN,327.335815,420.853107,0.0,20.0,164.0,455.0,2319.0
nrOfConversations,1209.0,NaN,NaN,NaN,241.918114,674.592881,0.0,20.0,67.0,226.0,12642.0
longestConversation,1209.0,NaN,NaN,NaN,139.11828,226.28775,0.0,27.0,69.0,161.0,2264.0
longestConversationInDays,1209.0,NaN,NaN,NaN,166.403639,323.848949,0.0,7.0,32.0,153.0,2284.0
averageConversationLength,1209.0,NaN,NaN,NaN,9.809123,18.071807,0.0,3.66,6.41,10.82,461.0
averageConversationLengthInDays,1209.0,NaN,NaN,NaN,3.66488,5.915688,0.0,0.76,1.83,4.02,92.71
medianConversationLength,1209.0,NaN,NaN,NaN,4.275434,27.997121,0.0,1.0,2.0,3.0,920.0
medianConversationLengthInDays,1209.0,NaN,NaN,NaN,0.524231,5.939479,0.0,0.0,0.006759,0.092465,185.19294
nrOfOneMessageConversations,1209.0,NaN,NaN,NaN,75.727047,230.038166,0.0,5.0,19.0,65.0,4807.0
percentOfOneMessageConversations,1209.0,NaN,NaN,NaN,30.972862,18.310761,0.0,19.05,30.21,41.18,100.0
nrOfGhostingsAfterInitialMessage,1209.0,NaN,NaN,NaN,29.519438,149.191069,0.0,0.0,3.0,15.0,4408.0
no_of_matches,1209.0,NaN,NaN,NaN,542.214227,1515.892456,0.0,9.0,108.0,468.0,23758.0
no_of_msgs_sent,1209.0,NaN,NaN,NaN,1884.516956,4425.48433,0.0,123.0,520.0,1782.0,61881.0
no_of_msgs_received,1209.0,NaN,NaN,NaN,1793.08354,4219.296682,0.0,117.0,499.0,1760.0,56173.0
swipe_likes,1209.0,NaN,NaN,NaN,14643.898263,37623.882473,0.0,317.0,3484.0,13887.0,705781.0
swipe_passes,1209.0,NaN,NaN,NaN,26399.340778,49869.115465,0.0,1146.0,8878.0,28210.0,550653.0
ageFilterMin,1209.0,NaN,NaN,NaN,20.467328,3.340123,18.0,18.0,19.0,22.0,46.0
ageFilterMax,1209.0,NaN,NaN,NaN,95.219189,239.492885,18.0,26.0,30.0,38.0,1000.0
instagram,1209,2,False,942,NaN,NaN,NaN,NaN,NaN,NaN,NaN
spotify,1209,2,False,752,NaN,NaN,NaN,NaN,NaN,NaN,NaN
user_age,1209.0,NaN,NaN,NaN,24.39206,7.359173,0.0,20.0,23.0,27.0,137.0

,% nulos,% no_nulos,tipo_dato,num_valores_unicos
_id,0.0%,100.0%,object,1209
sum_app_opens,0.0%,100.0%,int64,927
no_of_days,0.0%,100.0%,int64,595
nrOfConversations,0.0%,100.0%,int64,449
longestConversation,0.0%,100.0%,int64,356
longestConversationInDays,0.0%,100.0%,int64,394
averageConversationLength,0.0%,100.0%,float64,826
averageConversationLengthInDays,0.0%,100.0%,float64,605
medianConversationLength,0.0%,100.0%,int64,35
medianConversationLengthInDays,0.0%,100.0%,float64,729
nrOfOneMessageConversations,0.0%,100.0%,int64,246
percentOfOneMessageConversations,0.0%,100.0%,float64,745
nrOfGhostingsAfterInitialMessage,0.0%,100.0%,int64,157
no_of_matches,0.0%,100.0%,int64,563
no_of_msgs_sent,0.0%,100.0%,int64,867
no_of_msgs_received,0.0%,100.0%,int64,868
swipe_likes,0.0%,100.0%,int64,952
swipe_passes,0.0%,100.0%,int64,969
birthDate,0.0%,100.0%,object,1071
ageFilterMin,0.0%,100.0%,int64,20
ageFilterMax,0.0%,100.0%,int64,46
cityName,0.0%,100.0%,object,444
country,0.0%,100.0%,object,57
createDate,0.0%,100.0%,object,879
education,0.0%,100.0%,object,2
gender,0.0%,100.0%,object,2
interestedIn,0.0%,100.0%,object,3
instagram,0.0%,100.0%,bool,2
spotify,0.0%,100.0%,bool,2
jobTitle,0.0%,100.0%,object,314
user_age,0.0%,100.0%,int64,39